# Copyright 2020 by Jiuguang Wang (www.robo.guru)
# All rights reserved.
# This file is part of dayone2latex and is released under the MIT License.
# Please see the LICENSE file that should have been included as part of
# this package.


[tool.black]
# `extend-exclude` is not honored when `black` is passed a file path explicitly,
# as is typical when `black` is invoked via `pre-commit`.
force-exclude = '''
/(
  build/.*
)/
'''
include = '\.pyi?$'
line-length = 79
preview = true
target-version = ['py310']

[tool.mypy]
check_untyped_defs = true
disallow_untyped_defs = true
explicit_package_bases = true
ignore_missing_imports = true
no_implicit_optional = true
python_version = "3.10"
strict_equality = true
warn_redundant_casts = true
warn_unreachable = true

[[tool.mypy.overrides]]
disallow_untyped_defs = true
module = "mypy-scripts.*"

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = "matplotlib.*"

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = "setuptools.*"

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = "scipy.*"

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = "pandas.*"

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = "seaborn.*"

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = "chart_studio.*"

[tool.ruff]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
# Exclude a variety of commonly ignored directories.
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv"
]
# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
ignore = []
# Same as Black.
line-length = 79
# Enable pycodestyle (`E`), Pyflakes (`F`), and import sorting (`I`)
select = ["E", "F", "I"]
# Assume Python 3.10.
target-version = "py310"
unfixable = []

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.setuptools]
packages = ["agenoria", "config", "data"]
